import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import InfoPageLayout from "../components/InfoPageLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <InfoPageLayout>
          <h1 style={{ fontSize: 40, fontWeight: 700, marginBottom: 24 }}>
            TRANSPORTE ESCOLAR
          </h1>
          <p style={{ fontSize: 18, color: "#333", marginBottom: 24 }}>
            Con más de 22 años de experiencia, dobleVIA se especializa en el
            traslado seguro y puntual de estudiantes. Nuestro servicio de
            transporte escolar ofrece tranquilidad a instituciones educativas y
            familias al contar con:
          </p>
          <ul
            style={{
              fontSize: 17,
              color: "#222",
              marginBottom: 24,
              paddingLeft: 24,
            }}
          >
            <li style={{ marginBottom: 12 }}>
              <b>Monitoreo GPS en Tiempo Real:</b> Cada vehículo está equipado
              con rastreo GPS para que las familias puedan verificar la
              ubicación y ruta en tiempo real.
            </li>
            <li style={{ marginBottom: 12 }}>
              <b>Personal Capacitado:</b> Conductores y asistentes altamente
              capacitados en servicio al cliente, garantizando un entorno seguro
              y amigable para los estudiantes.
            </li>
            <li>
              <b>Mantenimiento Preventivo:</b> Riguroso plan de para asegurar la
              óptima condición de los vehículos en cada traslado.
            </li>
          </ul>
        </InfoPageLayout>
        <footer className={styles.footer}>
          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/file.svg"
              alt="File icon"
              width={16}
              height={16}
            />
            Learn
          </a>
          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/window.svg"
              alt="Window icon"
              width={16}
              height={16}
            />
            Examples
          </a>
          <a
            href="https://nextjs.org?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/globe.svg"
              alt="Globe icon"
              width={16}
              height={16}
            />
            Go to nextjs.org →
          </a>
        </footer>
      </div>
    </>
  );
}
